In [75]:
import pandas as pd

In [76]:
data = pd.read_excel('Book1.xlsx') #, index_col='index')
data

,Веса,index,Фактор,Петр,Иннокентий,Георгий,Олег,Алексей,Дмитрий
0,4,1,Стаж,5,3,1,10,5,7
1,8,2,"Кол-во повышений, нормированных на 5 лет",3,5,10,2,5,5
2,10,3,Кол-во «лайков» за лучшего сотрудника за год,39,23,3,19,13,42
3,0,4,Голосование,7,7,8,5,6,10

Задача: определить лучшего сотрудника в компании на основании имеющихся данных.

Среди данных, имеем:
1) Стаж в компании
2) Кол-во повышений, нормированное на 5 лет (если стаж 1 год то *5, так у Олега получилось 10, хотя по факту имеет лишь 2 повышения за год)
3) Кол-во лайков за лучшего сотрудника на портале

А также, мы попросили уполномоченных сотрудников, проголосовать за лучшего сотрудника и по их мнению, + разметить веса по параметрам (от наиболее важного к наименее важному)

Надо подобрать алгоритм, чтобы могли выйти на результат голосования, через первоначально имеющиеся данные.

Осмотрим данные:

In [77]:
data.loc[4] = [0,4,'Оценка',0,0,0,0,0,0] #Обращаемся к 4 строке по индексу (еще не существует) и добавляем данные строкой
data

,Веса,index,Фактор,Петр,Иннокентий,Георгий,Олег,Алексей,Дмитрий
0,4,1,Стаж,5,3,1,10,5,7
1,8,2,"Кол-во повышений, нормированных на 5 лет",3,5,10,2,5,5
2,10,3,Кол-во «лайков» за лучшего сотрудника за год,39,23,3,19,13,42
3,0,4,Голосование,7,7,8,5,6,10
4,0,4,Оценка,0,0,0,0,0,0

In [78]:
data.loc[5] = data.loc[3] #Так можно сделать дубль строки
data

,Веса,index,Фактор,Петр,Иннокентий,Георгий,Олег,Алексей,Дмитрий
0,4,1,Стаж,5,3,1,10,5,7
1,8,2,"Кол-во повышений, нормированных на 5 лет",3,5,10,2,5,5
2,10,3,Кол-во «лайков» за лучшего сотрудника за год,39,23,3,19,13,42
3,0,4,Голосование,7,7,8,5,6,10
4,0,4,Оценка,0,0,0,0,0,0
5,0,4,Голосование,7,7,8,5,6,10

In [79]:
data = data.drop(index=3).reset_index() #Дропаем строку с индексом 3, затем пересчитываем индексы (после удаления пересчитаются)
data

,level_0,Веса,index,Фактор,Петр,Иннокентий,Георгий,Олег,Алексей,Дмитрий
0,0,4,1,Стаж,5,3,1,10,5,7
1,1,8,2,"Кол-во повышений, нормированных на 5 лет",3,5,10,2,5,5
2,2,10,3,Кол-во «лайков» за лучшего сотрудника за год,39,23,3,19,13,42
3,4,0,4,Оценка,0,0,0,0,0,0
4,5,0,4,Голосование,7,7,8,5,6,10

In [80]:
data.loc[4,'index'] = 5 #Исправляем столбец index 4>5 в строке с индексом 4 (последняя строка)
data

,level_0,Веса,index,Фактор,Петр,Иннокентий,Георгий,Олег,Алексей,Дмитрий
0,0,4,1,Стаж,5,3,1,10,5,7
1,1,8,2,"Кол-во повышений, нормированных на 5 лет",3,5,10,2,5,5
2,2,10,3,Кол-во «лайков» за лучшего сотрудника за год,39,23,3,19,13,42
3,4,0,4,Оценка,0,0,0,0,0,0
4,5,0,5,Голосование,7,7,8,5,6,10

In [81]:
del data['level_0'] #Удаляем level_0
data

,Веса,index,Фактор,Петр,Иннокентий,Георгий,Олег,Алексей,Дмитрий
0,4,1,Стаж,5,3,1,10,5,7
1,8,2,"Кол-во повышений, нормированных на 5 лет",3,5,10,2,5,5
2,10,3,Кол-во «лайков» за лучшего сотрудника за год,39,23,3,19,13,42
3,0,4,Оценка,0,0,0,0,0,0
4,0,5,Голосование,7,7,8,5,6,10

In [82]:
data.index = data['index']; del data['index'] #Задаем индекс, убираем лишнее
data

,Веса,Фактор,Петр,Иннокентий,Георгий,Олег,Алексей,Дмитрий
index,,,,,,,,
1,4,Стаж,5,3,1,10,5,7
2,8,"Кол-во повышений, нормированных на 5 лет",3,5,10,2,5,5
3,10,Кол-во «лайков» за лучшего сотрудника за год,39,23,3,19,13,42
4,0,Оценка,0,0,0,0,0,0
5,0,Голосование,7,7,8,5,6,10

In [83]:
for name in ['Петр','Иннокентий','Георгий','Олег','Алексей','Дмитрий']: #Для всех столбцов с именем,
    data.loc[4,name] = sum(data['Веса'] * data[name])                   #Добавляем в строку с индексом 4 значения помноженные на веса

In [84]:
data

,Веса,Фактор,Петр,Иннокентий,Георгий,Олег,Алексей,Дмитрий
index,,,,,,,,
1,4,Стаж,5,3,1,10,5,7
2,8,"Кол-во повышений, нормированных на 5 лет",3,5,10,2,5,5
3,10,Кол-во «лайков» за лучшего сотрудника за год,39,23,3,19,13,42
4,0,Оценка,434,282,114,246,190,488
5,0,Голосование,7,7,8,5,6,10

In [85]:
df = data.T #Транспонируем
df.columns = data.T.loc['Фактор']

Пошаговое объяснение команды
Эта строка кода выполняет присваивание новых заголовков столбцов для DataFrame df на основе данных из другого DataFrame data.

Разбор по частям
data.T — транспонирует DataFrame data, то есть меняет местами строки и столбцы. Теперь то, что было строками, стало столбцами, и наоборот.
.loc['Фактор'] — выбирает строку (в транспонированном DataFrame это была колонка) с индексом 'Фактор'. В результате получается серия (одномерный массив), где индексы — это старые имена столбцов, а значения — новые названия.
df.columns = ... — присваивает эти значения в качестве новых заголовков столбцов для DataFrame df.

In [86]:
df

Фактор,Стаж,"Кол-во повышений, нормированных на 5 лет",Кол-во «лайков» за лучшего сотрудника за год,Оценка,Голосование
Веса,4,8,10,0,0
Фактор,Стаж,"Кол-во повышений, нормированных на 5 лет",Кол-во «лайков» за лучшего сотрудника за год,Оценка,Голосование
Петр,5,3,39,434,7
Иннокентий,3,5,23,282,7
Георгий,1,10,3,114,8
Олег,10,2,19,246,5
Алексей,5,5,13,190,6
Дмитрий,7,5,42,488,10

In [87]:
df = data.T # Транспонируем данные, строки = люди
df.columns = data.T.loc['Фактор']
coef_experts = df.loc['Веса'].iloc[:3] # Сохраним веса экспертов
df = df.drop(index=['Фактор', 'Веса'])

In [103]:
df

Фактор,Стаж,"Кол-во повышений, нормированных на 5 лет",Кол-во «лайков» за лучшего сотрудника за год,Оценка,Голосование,pred
Петр,5,3,39,434,7,7.3
Иннокентий,3,5,23,282,7,6.7
Георгий,1,10,3,114,8,8.2
Олег,10,2,19,246,5,5.1
Алексей,5,5,13,190,6,5.9
Дмитрий,7,5,42,488,10,9.9

Теперь построим линейную регресиию, в качестве известных x передадим известные нам фичи, в качестве y будут выступать результаты голосования уполномоченных сотрудников, тем самым попробуем подогнать данные под их экспертную оценку

In [89]:
X = df[['Стаж','Кол-во повышений, нормированных на 5 лет','Кол-во «лайков» за лучшего сотрудника за год']]
y = df['Голосование']

In [90]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X, y)
print('R2', reg.score(X, y), 'coef', reg.coef_, 'bias', reg.intercept_) #Выведем R2, кэфы и биас для понимания (свободный член, для подгонки под результат более точно)

R2 0.9817346018617825 coef [0.21198975 0.87119221 0.12238052] bias -1.1197235340846907

In [91]:
df['pred'] = round((reg.coef_ * X).sum(axis=1) + reg.intercept_,1)

In [92]:
df['pred']

Петр          7.326642
Иннокентий    6.686959
Георгий        8.17133
Олег          5.067788
Алексей       5.887133
Дмитрий       9.860148
Name: pred, dtype: object

In [93]:
import numpy as np
df['pred'] = np.round(reg.predict(X), 1)

In [94]:
df['pred']

Петр          7.3
Иннокентий    6.7
Георгий       8.2
Олег          5.1
Алексей       5.9
Дмитрий       9.9
Name: pred, dtype: float64

In [105]:
df

Фактор,Стаж,"Кол-во повышений, нормированных на 5 лет",Кол-во «лайков» за лучшего сотрудника за год,Оценка,Голосование,pred
Петр,5,3,39,434,7,7.3
Иннокентий,3,5,23,282,7,6.7
Георгий,1,10,3,114,8,8.2
Олег,10,2,19,246,5,5.1
Алексей,5,5,13,190,6,5.9
Дмитрий,7,5,42,488,10,9.9

Как видим, рассчитанные предикторы совпадают с экспертной оценкой.
Теперь, мы можем рассчитать эту метрику для любого сотрудника

Проверим, посчитаем оценку для второго Петра (с такими же данными 5,3,39) и второго Олега (10,2,19)

In [122]:
# Ваши новые данные
N = np.array([[5, 3, 39]])  # Обратите внимание на двойные скобки!

# Получение прогноза
prediction = reg.predict(N)
print('Прогноз:', prediction)

Прогноз: [7.32664221]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [123]:
# Ваши новые данные
N = np.array([[10, 2, 19]])  # Обратите внимание на двойные скобки!

# Получение прогноза
prediction = reg.predict(N)
print('Прогноз:', prediction)

Прогноз: [5.06778834]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(